### ISSUE TITLE
Headers do not get added to requests

### ISSUE THREAD

**Issue by araines** [Behatch/contexts#105]
Using the following feature:

```
Feature: Listing sports

  Scenario: Successful listing of seeded sports                    # features/functional/sports/index.feature:3
    Given I add "Accept" header equal to "application/json"        # Sanpi\Behatch\Context\RestContext::iAddHeaderEqualTo()
    And I add "Content-type" header equal to "application/json"    # Sanpi\Behatch\Context\RestContext::iAddHeaderEqualTo()
    When I send a GET request to "/sports"
```

Using TCPdump to see what is actually being sent:

```
GET /sports HTTP/1.1
Host: test.apisportsdata.sportlobster.dev
User-Agent: Symfony2 BrowserKit
```

None of the headers I have specified are actually sent.

Composer:

```
    "require-dev": {
        "behat/behat": "~3.0",
        "behat/mink-goutte-driver": "~1.1",
        "behatch/contexts": "dev-master",
        "phpspec/phpspec": "~2.0",
        "phpunit/phpunit": "~4.1",
        "way/generators": "2.*"
    },
```

Behat.yml:

```
default:
    extensions:
        Behat\MinkExtension:
            base_url: 'http://localhost'
            default_session: goutte
            goutte: ~
        Sanpi\Behatch\Extension: ~
    suites:
        functional:
            paths: [ %paths.base%/features/functional ]
            contexts:
                - LaravelFeatureContext
                - Behat\MinkExtension\Context\MinkContext
                - behatch:browser
                - behatch:debug
                - behatch:system
                - behatch:json:
                    evaluationMode: javascript
                - behatch:table
                - behatch:rest
                - behatch:xml
```
