### ISSUE TITLE
Impossible to use context behatch:json or rest without triggering an error

### ISSUE THREAD

**Issue by tristanbes** [Behatch/contexts#112]
Hi,

When I use contexts : `behatch:json` or `behatch:rest` I got : 
```
[Symfony\Component\Debug\Exception\ContextErrorException]             
  Warning: preg_match() expects parameter 2 to be string, object given 
```

As soon as I remove them, the error disappear.
Has the documentation some step missing ?

Using Behat 3+ : 
```json
        "behat/behat": "3.0.*@dev",
        "behat/symfony2-extension": "dev-master",
        "behat/mink-extension": "2.0.*@dev",
        "behat/common-contexts": "1.2.*@dev",
        "sensiolabs/behat-page-object-extension": "2.0.*@dev",
        "vipsoft/doctrine-data-fixtures-extension": "3.0.*@dev",
        "behatch/contexts": "dev-master",
        "behat/mink": "dev-master",
        "behat/mink-browserkit-driver": "dev-master",
        "behat/mink-goutte-driver": "dev-master",
        "behat/mink-selenium2-driver": "1.2.*@dev",
        "behat/web-api-extension": "1.0.*@dev"
```

with configuration : 

```yml
default:
    autoload: %paths.base%/features/Context
    extensions:
        Behat\MinkExtension:
            base_url:   http://xxx.xxxx.dev/app_test.php/
            files_path: app/features/files
            default_session:    goutte
            javascript_session: selenium2
            goutte:    ~
            selenium2: ~
        Behat\Symfony2Extension:
            kernel:
                env:   test
                debug: true
        VIPSoft\DoctrineDataFixturesExtension\Extension:
            lifetime:    feature
            autoload:    false
            directories:
                - app/features/Context/Fixtures
            fixtures:    ~
            migrations: ~
        Behat\WebApiExtension:
            base_url: http://xxx.xxx.dev/app_test.php/
        Sanpi\Behatch\Extension: ~
    suites:
        default:
            contexts:
                - Context\FeatureContext
                - Behat\WebApiExtension\Context\WebApiContext
                - behatch:table
                - behatch:json
                - behatch:rest

    translation:
        locale: en
```
