### ISSUE TITLE
Symfony2 extension compatibility

### ISSUE THREAD

**Issue by sanpii** [Behatch/contexts#119]
Ok, travis back to green, now we can work on the big issue with [Behat/Symfony2Extension](https://github.com/Behat/Symfony2Extension/) (#55, #98, #101, #110 and #118).

All issues is in the rest context, this confirms @stof’s [comment](https://github.com/Behatch/contexts/pull/75#issuecomment-44983348):

> The rest-context is a huge mistake altogether. Mink is not a REST client (browsers are not REST clients either). There is no point using the Mink driver to perform the REST API calls. It is the wrong tool for the job.

Any idea?

**Comment by sanpii** [comment]
Scrutinizer would be probably happy too if the rest context is rewritten: https://scrutinizer-ci.com/g/Behatch/contexts/issues/master/files/src/Context/RestContext.php?selectedLabels[0]=9&orderField=path&order=asc

**Comment by sanpii** [comment]
I just push a new branch [symfony2](https://github.com/Behatch/contexts/tree/symfony2) fixed this issue. Feedback welcome :smiley:

**Comment by koorb** [comment]
@sanpii I've just pulled the browser-kit branch and run the tests and I'm getting the same error.
```
Call to undefined method Symfony\Component\HttpKernel\Client::setHeader()
```

**Comment by koorb** [comment]
Any thoughts on this? I am using it along with a https://github.com/laracasts/Behat-Laravel-Extension could there be a conflict? Perhaps I'm not configuring be behatch properly?

``` yaml
default:

  extensions:
    Laracasts\Behat: ~
    Sanpi\Behatch\Extension: ~
    Behat\MinkExtension:
      show_cmd: "/Applications/Safari.app/Contents/MacOS/Safari %s"
      default_session: laravel
      laravel: ~

  suites:
    default:
      contexts:
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - behatch:json
        - behatch:rest
```
