### ISSUE TITLE
Only use SystemContext

### ISSUE THREAD

**Issue by tophsic** [Behatch/contexts#148]
To test command lines tool, I do not need http_call services required in `Extension::load` method.

Do you think it is a good idea to add a parameter to allow to skip `http_call` loading?

PR is coming if so.

**Comment by sanpii** [comment]
It’s just a service declaration. If you don’t load a class needs it, no instance is created.

**Comment by tophsic** [comment]
I should have begin by that

My composer file:

```json
{
    "name": "my/project",
    "type": "project",
    "require": {
        "php": ">=5.4"
    },
    "require-dev": {
        "behatch/contexts": "^2.3"
    }
}
```

My Behat configuration:

```yaml
default:
    suites:
        core:
            paths:
                - %paths.base%/features
            contexts:
                - FeatureContext
                - behatch:system:
                    root: "."

    extensions:
        Sanpi\Behatch\Extension: ~
```

```bash
# vendor/bin/behat
                                                                                               
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                   
  The service "behatch.http_call.listener" has a dependency on a non-existent service "mink".  
```

**Comment by tophsic** [comment]
Fool I am

```yaml
default:
    suites:
        core:
            paths:
                - %paths.base%/features
            contexts:
                - FeatureContext
                - Sanpi\Behatch\Context\SystemContext
```

is working
