### ISSUE TITLE
How to obtain and set JWT Token

### ISSUE THREAD

**Issue by cve** [Behatch/contexts#182]
Hi,

I'm using https://github.com/lexik/LexikJWTAuthenticationBundle for authentication, and my question is how to simply loggin user with Behat step, I'm trying the following, but it's not working:

```php
private function setToken($username, $password)
{
    $params = [
        '_username' => $username,
        '_password' => $password,
    ];

    $this->restContext->iAddHeaderEqualTo('Content-Type', 'application/json');
    $this->restContext->iSendARequestToWithBody(
        'POST',
        '/api/login_check',
        new PyStringNode([json_encode($params)], 0)
    );
    $token = json_decode($this->jsonContext->printLastJsonResponse())['token'];
    $this->restContext->iAddHeaderEqualTo('Authorization', 'Bearer '.$token);
}
```

**Comment by cve** [comment]
Ok, I'm figured it out, it's simpler:

#### behat.yml

```yml
default:
    extensions:
        Sanpi\Behatch\Extension: ~
    suites:
        default:
            contexts:
                - FeatureContext:
                    JWTManager: '@lexik_jwt_authentication.jwt_manager'
                - behatch:json
                - behatch:rest
```

#### FeatureContext dependency

```php
/**
 * FeatureContext constructor.
 * @param JWTManager $JWTManager
 */
public function __construct(JWTManager $JWTManager)
{
    $this->JWTManager = $JWTManager;
}
```

#### setToken method

```php
private function setToken(UserInterface $user)
{
    $token = $this->JWTManager->create($user);
    $this->restContext->iAddHeaderEqualTo('Authorization', 'Bearer '.$token);
}
```
