### ISSUE TITLE
Move the contexts configuration into the context constructors and make it easier to use them (3.0)

### ISSUE THREAD

**Issue by everzet** [Behatch/contexts#60]
You can simplify things even further in 3.0:
- You can move away from custom configuration with https://github.com/Behat/Behat/pull/446
- Also, by implementing your own custom [`ClassResolver`](https://github.com/Behat/Behat/blob/3.0/src/Behat/Behat/Context/ContextClass/ClassResolver.php), you can simplify contexts referencing

Basically, those things put together will allow you to do something like this:

``` yml
default:
    suites:
        core:
            contexts:
                behatch:debug:
                    screenshotDir: '/tmp'
```

`behatch:debug` will be resolved to `Sanpi\Behatch\Context\DebugContext` via your custom `ClassResolver`. Then `screenshotDir` will be passed to it as a simple constructor argument (matching by name).
